title: Interconnection Techniques Research Group
logo: /assets/img/logo.png
description: Interconnection Techniques Research Group (ItTi) focuses on the interconnection techniques for chip-level and server-level communication in AI acceleration and high-performance computing. 
theme: jekyll-theme-minimal
